### ISSUE TITLE
No data populating

### ISSUE THREAD

**Issue by moshin34** [tderflinger/MMM-GConnect#4]
Seems like such a simple install.  The module renders properly, just none of my data!    Idk why I cant seem to get this one going.

[30.09.2023 12:59.33.961] [ERROR] (node:3804) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'startTimeLocal')
    at getLastActivityDate (/home/mo/MagicMirror/modules/MMM-GConnect/node_helper.js:6:43)
    at Class.socketNotificationReceived (/home/mo/MagicMirror/modules/MMM-GConnect/node_helper.js:28:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

(Use `electron --trace-warnings ...` to show where the warning was created)
[30.09.2023 12:59.33.962] [ERROR] (node:3804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[30.09.2023 12:59.33.979] [WARN]  Unhandled rejection StatusCodeError: 403 - "{\"clientMessage\":\"Reference Error ID in error logs for further information\",\"errorId\":\"3e7b86b5-3a30-4418-a9ed-5fb696180472\",\"error\":\"WebApplicationException\"}"
    at new StatusCodeError (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/request/request.js:185:22)
    at onRequestComplete (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/cloudscraper/index.js:629:3)
    at onRequestResponse (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/cloudscraper/index.js:207:5)
    at Request.<anonymous> (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/mo/MagicMirror/modules/MMM-GConnect/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by tderflinger** [comment]
Hi, thanks for your feedback.
Garmin recently changed their login routine, thus MMM-GConnect no longer works. The underlying library that I use is garmin-connect. They have the issue open here: https://github.com/Pythe1337N/garmin-connect/issues/55
Currently, they are working on a fix. I will update MMM-GConnect once the fix is finished.
-Thomas

**Comment by moshin34** [comment]
Sounds excellent, thanks! I am fairly new to all this, but keen to learn.
  Appreciate all that you do!

**Comment by tderflinger** [comment]
@moshin34, I updated the new library and it should now work. Please update to the latest code version. Also, you have to add your login creditials to the `garmin.config.json` file. This is now a requirement by the library.
Have fun!
